/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const snapshot = [
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1582905952',
            max: 0,
            min: 0,
            name: 'method',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2279338944',
        indexes: [
          'CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (collectionRef,recordRef)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_mfas',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 8,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 0,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: true,
            id: 'text3866985172',
            max: 0,
            min: 0,
            name: 'sentTo',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_1638494021',
        indexes: [
          'CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (collectionRef, recordRef)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_otps',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2462348188',
            max: 0,
            min: 0,
            name: 'provider',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1044722854',
            max: 0,
            min: 0,
            name: 'providerId',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2281828961',
        indexes: [
          'CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (collectionRef, recordRef, provider)',
          'CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (collectionRef, provider, providerId)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_externalAuths',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text4228609354',
            max: 0,
            min: 0,
            name: 'fingerprint',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_4275539003',
        indexes: [
          'CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (collectionRef, recordRef, fingerprint)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_authOrigins',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 86400,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: null,
        deleteRule: null,
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            help: '',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: 'pbc_3142635823',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE `email` != ''",
        ],
        listRule: null,
        manageRule: null,
        mfa: {
          duration: 1800,
          enabled: false,
          rule: '',
        },
        name: '_superusers',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: '',
            id: '',
            name: '',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: true,
        type: 'auth',
        updateRule: null,
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 259200,
        },
        viewRule: null,
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 604800,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: '',
        deleteRule: 'id = @request.auth.id',
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            help: '',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1579384326',
            max: 255,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'file376926767',
            maxSelect: 1,
            maxSize: 0,
            mimeTypes: ['image/jpeg', 'image/png', 'image/svg+xml', 'image/gif', 'image/webp'],
            name: 'avatar',
            presentable: false,
            protected: false,
            required: false,
            system: false,
            thumbs: null,
            type: 'file',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: '_pb_users_auth_',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''",
        ],
        listRule: 'id = @request.auth.id',
        manageRule: null,
        mfa: {
          duration: 1800,
          enabled: false,
          rule: '',
        },
        name: 'users',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: 'avatar',
            id: '',
            name: 'name',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: false,
        type: 'auth',
        updateRule: 'id = @request.auth.id',
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 259200,
        },
        viewRule: 'id = @request.auth.id',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1941015338',
            name: 'single_volume',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool989355118',
            name: 'completed',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'select2363381545',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Book', 'Game', 'Movie', 'Show'],
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_2047489680',
            help: '',
            hidden: false,
            id: 'relation1874629670',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_3522289653',
        indexes: [],
        listRule: '',
        name: 'media_series',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3522289653',
            help: '',
            hidden: false,
            id: 'relation974127405',
            maxSelect: 1,
            minSelect: 0,
            name: 'series',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'number2155046657',
            max: null,
            min: null,
            name: 'sequence_number',
            onlyInt: true,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: 'date3882452845',
            max: '',
            min: '',
            name: 'release_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: 'date3660447513',
            max: '',
            min: '',
            name: 'purchase_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1886949452',
            name: 'in_delivery',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'url1336264112',
            name: 'shopping_link',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1219621782',
            help: '',
            hidden: false,
            id: 'relation1874629670',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_87875696',
        indexes: [],
        listRule: '',
        name: 'series_volumes',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text245846248',
            max: 0,
            min: 0,
            name: 'label',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_1219621782',
        indexes: [],
        listRule: '',
        name: 'volume_tags',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '_clone_Bik6',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_RZDN',
            name: 'single_volume',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_M8TT',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Book', 'Game', 'Movie', 'Show'],
          },
          {
            help: '',
            hidden: false,
            id: 'json1082410845',
            maxSize: 1,
            name: 'highest_volume_number',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_2047489680',
            help: '',
            hidden: false,
            id: '_clone_8ik9',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_U1xc',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_RCxK',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_817363172',
        indexes: [],
        listRule: '',
        name: 'orphaned_media_series',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          "SELECT\n  id,\n  name,\n  single_volume,\n  type,\n  (SELECT MAX(series_volumes.sequence_number) FROM series_volumes WHERE series_volumes.series = media_series.id) as highest_volume_number,\n  tags,\n  created,\n  updated\nFROM media_series\nWHERE media_series.completed = 0 AND media_series.id NOT IN (\n  SELECT DISTINCT series\n  FROM series_volumes\n  WHERE series_volumes.purchase_date = '' OR\n    (series_volumes.purchase_date <> '' AND series_volumes.in_delivery = 1)\n)",
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text245846248',
            max: 0,
            min: 0,
            name: 'label',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_2047489680',
        indexes: [],
        listRule: '',
        name: 'series_tags',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '_clone_Ufh3',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_AJl2',
            name: 'single_volume',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_QsgW',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Book', 'Game', 'Movie', 'Show'],
          },
          {
            help: '',
            hidden: false,
            id: 'json1082410845',
            maxSize: 1,
            name: 'highest_volume_number',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_2047489680',
            help: '',
            hidden: false,
            id: '_clone_oQvc',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_K7fO',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_Ulk8',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_3849473420',
        indexes: [],
        listRule: '',
        name: 'incomplete_media_series',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          'SELECT\n  id,\n  name,\n  single_volume,\n  type,\n  (SELECT MAX(series_volumes.sequence_number) FROM series_volumes WHERE series_volumes.series = media_series.id) as highest_volume_number,\n  tags,\n  created,\n  updated\nFROM media_series\nWHERE media_series.completed = 0',
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '_clone_2jma',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_BgRO',
            name: 'single_volume',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_RfaF',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Book', 'Game', 'Movie', 'Show'],
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_2047489680',
            help: '',
            hidden: false,
            id: '_clone_Q4Fm',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_TSDE',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_nDKX',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_1183830025',
        indexes: [],
        listRule: '',
        name: 'completed_media_series',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          'SELECT\n  id,\n  name,\n  single_volume,\n  type,\n  tags,\n  created,\n  updated\nFROM media_series\nWHERE media_series.completed = 1',
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '_clone_EWYB',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_R7Rh',
            name: 'single_volume',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_tO1Q',
            name: 'completed',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_CcLD',
            maxSelect: 1,
            name: 'type',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['Book', 'Game', 'Movie', 'Show'],
          },
          {
            help: '',
            hidden: false,
            id: 'json1082410845',
            maxSize: 1,
            name: 'highest_volume_number',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_2047489680',
            help: '',
            hidden: false,
            id: '_clone_O0M4',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_KkSD',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_bN4n',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_1398804675',
        indexes: [],
        listRule: '',
        name: 'all_media_series',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          'SELECT\n  id,\n  name,\n  single_volume,\n  completed,\n  type,\n  (SELECT MAX(series_volumes.sequence_number) FROM series_volumes WHERE series_volumes.series = media_series.id) as highest_volume_number,\n  tags,\n  created,\n  updated\nFROM media_series',
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3522289653',
            help: '',
            hidden: false,
            id: '_clone_9KWm',
            maxSelect: 1,
            minSelect: 0,
            name: 'series',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_m0A4',
            max: null,
            min: null,
            name: 'sequence_number',
            onlyInt: true,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_NjVZ',
            max: '',
            min: '',
            name: 'release_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_aJvY',
            max: '',
            min: '',
            name: 'purchase_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: '_clone_V7yA',
            name: 'shopping_link',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1219621782',
            help: '',
            hidden: false,
            id: '_clone_7Lmh',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_ZmFW',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_jmHu',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_590174504',
        indexes: [],
        listRule: '',
        name: 'collected_series_volumes',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          "SELECT id, series, sequence_number, release_date, purchase_date, shopping_link, tags, created, updated\nFROM series_volumes\nWHERE series_volumes.purchase_date <> '' AND series_volumes.in_delivery = 0",
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3522289653',
            help: '',
            hidden: false,
            id: '_clone_fXOJ',
            maxSelect: 1,
            minSelect: 0,
            name: 'series',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_QJZM',
            max: null,
            min: null,
            name: 'sequence_number',
            onlyInt: true,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_xu9k',
            max: '',
            min: '',
            name: 'release_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: '_clone_Ks3K',
            name: 'shopping_link',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1219621782',
            help: '',
            hidden: false,
            id: '_clone_UnJp',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_PzYG',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_iznV',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_2701442872',
        indexes: [],
        listRule: '',
        name: 'missing_series_volumes',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          "SELECT id, series, sequence_number, release_date, shopping_link, tags, created, updated\nFROM series_volumes\nWHERE series_volumes.purchase_date = '' AND series_volumes.in_delivery = 0",
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3522289653',
            help: '',
            hidden: false,
            id: '_clone_v5cW',
            maxSelect: 1,
            minSelect: 0,
            name: 'series',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_Wowq',
            max: null,
            min: null,
            name: 'sequence_number',
            onlyInt: true,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_BYfV',
            max: '',
            min: '',
            name: 'release_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_J04V',
            max: '',
            min: '',
            name: 'purchase_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: '_clone_ZUtQ',
            name: 'shopping_link',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1219621782',
            help: '',
            hidden: false,
            id: '_clone_0NTI',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_NsRg',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_TBtM',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_1547721829',
        indexes: [],
        listRule: '',
        name: 'in_delivery_series_volumes',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          "SELECT id, series, sequence_number, release_date, purchase_date, shopping_link, tags, created, updated\nFROM series_volumes\nWHERE series_volumes.purchase_date <> '' AND series_volumes.in_delivery = 1",
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3522289653',
            help: '',
            hidden: false,
            id: '_clone_ENRd',
            maxSelect: 1,
            minSelect: 0,
            name: 'series',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_MB2h',
            max: null,
            min: null,
            name: 'sequence_number',
            onlyInt: true,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_CdMk',
            max: '',
            min: '',
            name: 'release_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: '_clone_c7qy',
            name: 'shopping_link',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1219621782',
            help: '',
            hidden: false,
            id: '_clone_oAlQ',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_55iH',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_9NqF',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_2996037406',
        indexes: [],
        listRule: '',
        name: 'released_series_volumes',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          "SELECT id, series, sequence_number, release_date, shopping_link, tags, created, updated\nFROM series_volumes\nWHERE series_volumes.purchase_date = '' AND series_volumes.in_delivery = 0 AND series_volumes.release_date <> '' AND series_volumes.release_date <= DATETIME()",
        viewRule: '',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 0,
            min: 0,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3522289653',
            help: '',
            hidden: false,
            id: '_clone_wJ39',
            maxSelect: 1,
            minSelect: 0,
            name: 'series',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_CLST',
            max: null,
            min: null,
            name: 'sequence_number',
            onlyInt: true,
            presentable: false,
            required: true,
            system: false,
            type: 'number',
          },
          {
            help: '',
            hidden: false,
            id: '_clone_p4NV',
            max: '',
            min: '',
            name: 'release_date',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: '_clone_0tdi',
            name: 'shopping_link',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            cascadeDelete: false,
            collectionId: 'pbc_1219621782',
            help: '',
            hidden: false,
            id: '_clone_4AXR',
            maxSelect: 999,
            minSelect: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: '_clone_yV6Q',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: '_clone_Od8X',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_2113520697',
        indexes: [],
        listRule: '',
        name: 'upcoming_series_volumes',
        system: false,
        type: 'view',
        updateRule: null,
        viewQuery:
          "SELECT id, series, sequence_number, release_date, shopping_link, tags, created, updated\nFROM series_volumes\nWHERE series_volumes.purchase_date = '' AND series_volumes.in_delivery = 0 AND (series_volumes.release_date = '' OR series_volumes.release_date > DATETIME())",
        viewRule: '',
      },
    ];

    return app.importCollections(snapshot, false);
  },
  (app) => {
    return null;
  },
);
